#!/usr/sbin/nft -f

flush ruleset

# External Interface (uplink)
define EXT = wlan0

# Local Interfaces
define LOCAL = eth0*

table ip global {
	chain input {
		type filter hook input priority 0; policy drop;

		ct state established,related accept
		ct state invalid drop

		# allow connections
		iifname { lo, $EXT } accept
		iifname $LOCAL accept
	}
	chain forward {
		type filter hook forward priority 0; policy drop;

		ct state established,related accept
		ct state invalid drop

		iifname lo accept
		iifname $LOCAL accept
	}
}
table ip net {
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;

		#ip saddr 192.168.0.0/24 iifname $ETH0 oifname $EXT masquerade
		#ip saddr 192.168.101.0/24 iifname $ETH1 oifname $EXT masquerade
		oifname $EXT masquerade
	}
}
