targets:
  main:
    features:
      - bbbconfig
      - ramboot_then_flash
      - console
      - reset
      - wifi
      - online
      - olsr
    options:
      lan_ip: '10.248.248.49'
      lan_netmask: '255.255.255.240'
      lan_vlan: 104
      connected_port: lan
    resources:
      - RemotePlace:
          name: port4
    drivers:
      - GpioDigitalOutputDriver:
          name: powerdriver
          bindings:
            gpio: power # resouce name
      - GpioDigitalOutputDriver:
          name: resetdriver
          bindings:
            gpio: reset # resource name
      - DigitalOutputPowerDriver:
          bindings:
            output: powerdriver
      - DigitalOutputButtonDriver:
          delay: 7.0
          bindings:
            output: resetdriver
      - SerialDriver: {}
      - TFTPProviderDriver: {}
      - MikrotikUBootInteractionRamboot:
          image: "target"
          mac: "dc:2c:6e:c3:fa:b9"
          bootpip: "192.168.0.104"
          cycle_power: True
          hold_reset: True
          hold_timeout: 25
      - OpenWrtUBootDriver:
          prompt: 'IMPOSSIBLE' # we have a silent bootloader
          silent_uboot: True
          hold_reset_before_uboot: True
      - OpenWrtShellDriver:
          keyfile: "~/.ssh/id_rsa.pub"
          login_timeout: 240
      - OpenWrtUciDriver: {}
      - OpenWrtPackageDriver: {}
      - OpenWrtLuCIDriver: {}
      - SSHDriver:
          explicit_scp_mode: True
      - NetworkInterfaceDriver: {}
      - BBBConfigStrategy: {}
paths:
  backup: !template "$BASE/backup"
images:
  # filenames including a prefix of "/srv/tftp/testdevXX/" must be 128 char or less
  target: !template $LG_IMAGE
  rescue_ramboot: "firmware/openwrt-24.10.2-ipq40xx-mikrotik-mikrotik_sxtsq-5-ac-initramfs-kernel.bin"
  restore: "backup/restore.tar.gz"
imports:
  - ../../openwrt-testlab.py
  - ../../bbbconfig-testlab.py
