targets:
  main:
    features:
      - bbbconfig
      - ramboot_then_flash
      - console
      - reset
      - wifi
      - online
      - olsr
    options:
      lan_ip: '10.248.248.81'
      lan_netmask: '255.255.255.240'
      lan_vlan: 106
      connected_port: 'wan'
    resources:
      - RemotePlace:
          name: port6
    drivers:
      - GpioDigitalOutputDriver:
          name: powerdriver
          bindings:
            gpio: power # resouce name
      - GpioDigitalOutputDriver:
          name: resetdriver
          bindings:
            gpio: reset # resource name
      - DigitalOutputPowerDriver:
          bindings:
            output: powerdriver
      - DigitalOutputButtonDriver:
          delay: 7.0
          bindings:
            output: resetdriver
      - SerialDriver: {}
      - TFTPProviderDriver: {}
      - UBootInteractionBoot:
          commands:
            - boot
      - UBootInteractionRamboot:
          image: "target"
          mac: "44:d4:37:8c:13:78"
          bootpip: "192.168.0.106"
          commands:
            - net_init
            - bootp
            - bootm
      - OpenWrtUBootDriver:
          prompt: '->'
          autoboot: 'stop autoboot'
          boot_secret: 'a'
          boot_secret_nolf: True
      - OpenWrtShellDriver:
          keyfile: "~/.ssh/id_rsa.pub"
      - OpenWrtUciDriver: {}
      - OpenWrtPackageDriver: {}
      - OpenWrtLuCIDriver: {}
      - SSHDriver:
          explicit_scp_mode: True
      - NetworkInterfaceDriver: {}
      - BBBConfigStrategy: {}
paths:
  backup: !template "$BASE/backup"
images:
  # filenames including a prefix of "/srv/tftp/testdevXX" must be 128 char or less
  target: !template $LG_IMAGE
  rescue_ramboot: "firmware/openwrt-24.10.3-ramips-mt7621-genexis_pulse-ex400-initramfs-kernel.bin"
  factory: "firmware/freifunk-falter-1.5.0-snapshot-ramips-mt7621-genexis_pulse-ex400-factory.bin"
  sysupgrade: "firmware/freifunk-falter-1.5.0-snapshot-ramips-mt7621-genexis_pulse-ex400-sysupgrade.bin"
  restore: "backup/restore.tar.gz"
imports:
  - ../../openwrt-testlab.py
  - ../../bbbconfig-testlab.py
